import http from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual, createCipheriv, createHash } from 'node:crypto';
import path from 'node:path';

const PORT=Number(process.env.PORT||8787), ROOT=path.join(process.cwd(),'.traceguard-data'), DB=path.join(ROOT,'db.json'), VAULT=path.join(ROOT,'vault'), KEY_FILE=path.join(ROOT,'.vault-key');
let key;
const seed=[
  {id:'m1',site:'mirror-stream.net',type:'Video',confidence:98,status:'Action needed',age:'12 min ago'},
  {id:'m2',site:'social-repost.co',type:'Photo set',confidence:94,status:'Monitoring',age:'2 hrs ago'},
  {id:'m3',site:'forumvault.io',type:'Image',confidence:91,status:'Takedown sent',age:'Yesterday'},
  {id:'m4',site:'cliparchive.tv',type:'Video',confidence:87,status:'Removed',age:'Jul 14'}
];
async function load(){await mkdir(VAULT,{recursive:true});if(!key){if(process.env.CONTENT_PROTECT_MASTER_KEY)key=Buffer.from(process.env.CONTENT_PROTECT_MASTER_KEY,'hex');else if(existsSync(KEY_FILE))key=Buffer.from((await readFile(KEY_FILE,'utf8')).trim(),'hex');else{key=randomBytes(32);await writeFile(KEY_FILE,key.toString('hex'),{mode:0o600})}}if(!existsSync(DB)){const d={users:[],assets:[],cases:[],matches:seed,scans:[],subscriptions:[],audit:[],sessions:[]};await save(d);return d}const d=JSON.parse(await readFile(DB,'utf8'));d.scans||=[];d.subscriptions||=[];d.audit||=[];d.assets||=[];d.cases||=[];d.sessions||=[];d.sessions=d.sessions.filter(x=>new Date(x.expiresAt)>new Date());return d}
async function save(d){await writeFile(DB,JSON.stringify(d,null,2))}
const securityHeaders={'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self'; connect-src 'self'"};
function send(res,status,data,headers={}){res.writeHead(status,{...securityHeaders,'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(data))}
async function staticFile(req,res){const urlPath=decodeURIComponent(req.url.split('?')[0]),rel=urlPath==='/'?'index.html':urlPath.replace(/^\//,'');const requested=path.resolve(process.cwd(),'dist',rel);const distRoot=path.resolve(process.cwd(),'dist');if(!requested.startsWith(distRoot))return false;try{const data=await readFile(requested);const ext=path.extname(requested),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};res.writeHead(200,{...securityHeaders,'content-type':types[ext]||'application/octet-stream','cache-control':ext==='.html'?'no-cache':'public, max-age=31536000, immutable'});res.end(data);return true}catch{if(!path.extname(rel)){try{const data=await readFile(path.join(distRoot,'index.html'));res.writeHead(200,{...securityHeaders,'content-type':'text/html; charset=utf-8','cache-control':'no-cache'});res.end(data);return true}catch{}}return false}}
async function parse(req){const out=[];let n=0;for await(const c of req){n+=c.length;if(n>12e6)throw Error('large');out.push(c)}return out.length?JSON.parse(Buffer.concat(out)): {}}
function pass(p,s=randomBytes(16).toString('hex')){return {s,h:scryptSync(p,s,64).toString('hex')}}
function cookie(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')))}
function tokenHash(token){return createHash('sha256').update(token||'').digest('hex')}
function newSession(d,u){const token=randomBytes(32).toString('hex');d.sessions.push({tokenHash:tokenHash(token),userId:u.id,expiresAt:new Date(Date.now()+7*864e5).toISOString()});return token}
function userFor(req,d){const s=d.sessions.find(x=>x.tokenHash===tokenHash(cookie(req).cp_session));return d.users.find(x=>x.id===s?.userId)}
function safe(u){return {id:u.id,name:u.name,email:u.email,stageName:u.stageName,aliases:u.aliases||[],platforms:u.platforms||[],plan:u.plan,onboardingComplete:u.onboardingComplete,createdAt:u.createdAt}}
function vault(buf){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([c.update(buf),c.final()]);return Buffer.concat([iv,c.getAuthTag(),data])}
function audit(d,u,action,details={}){d.audit.unshift({id:randomUUID(),userId:u.id,action,details,at:new Date().toISOString()});d.audit=d.audit.slice(0,500)}

http.createServer(async(req,res)=>{try{
  if(!req.url.startsWith('/api/')){if(process.env.NODE_ENV==='production'&&await staticFile(req,res))return;return send(res,404,{error:'Not found'})}const d=await load(),route=req.url.split('?')[0];
  if(route==='/api/health')return send(res,200,{ok:true,mode:'local-secure'});
  if(route==='/api/auth/register'&&req.method==='POST'){const b=await parse(req);if(!b.email||!b.password||b.password.length<8)return send(res,400,{error:'Use a valid email and a password of at least 8 characters.'});if(d.users.some(x=>x.email===b.email.toLowerCase()))return send(res,409,{error:'Account already exists.'});const p=pass(b.password),u={id:randomUUID(),name:b.name||'Creator',stageName:b.stageName||'',email:b.email.toLowerCase(),salt:p.s,passwordHash:p.h,plan:'Protect',onboardingComplete:false,createdAt:new Date().toISOString()};d.users.push(u);const t=newSession(d,u);await save(d);return send(res,201,{user:safe(u)},{'set-cookie':`cp_session=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`})}
  if(route==='/api/auth/login'&&req.method==='POST'){const b=await parse(req),u=d.users.find(x=>x.email===String(b.email).toLowerCase());if(!u)return send(res,401,{error:'Email or password is incorrect.'});const h=scryptSync(b.password||'',u.salt,64);if(!timingSafeEqual(h,Buffer.from(u.passwordHash,'hex')))return send(res,401,{error:'Email or password is incorrect.'});const t=newSession(d,u);await save(d);return send(res,200,{user:safe(u)},{'set-cookie':`cp_session=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.NODE_ENV==='production'?'; Secure':''}`})}
  if(route==='/api/auth/logout'&&req.method==='POST'){d.sessions=d.sessions.filter(x=>x.tokenHash!==tokenHash(cookie(req).cp_session));await save(d);return send(res,200,{ok:true},{'set-cookie':'cp_session=; HttpOnly; SameSite=Strict; Secure; Path=/; Max-Age=0'})}
  const u=userFor(req,d);if(!u)return send(res,401,{error:'Authentication required.'});
  if(route==='/api/me')return send(res,200,{user:safe(u)});
  if(route==='/api/dashboard'){const assets=d.assets.filter(x=>x.userId===u.id),cases=d.cases.filter(x=>x.userId===u.id),scans=d.scans.filter(x=>x.userId===u.id);return send(res,200,{matches:d.matches,assets,cases,scans,subscription:d.subscriptions.find(x=>x.userId===u.id),audit:d.audit.filter(x=>x.userId===u.id).slice(0,20),stats:{matches:d.matches.length,review:d.matches.filter(x=>x.status==='Action needed').length,active:cases.filter(x=>x.status!=='Removed').length,removed:d.matches.filter(x=>x.status==='Removed').length,sources:scans[0]?.sourcesChecked||0}})}
  if(route==='/api/profile'&&req.method==='PATCH'){const b=await parse(req);u.name=b.name||u.name;u.stageName=b.stageName??u.stageName;u.aliases=Array.isArray(b.aliases)?b.aliases.slice(0,10):u.aliases||[];u.platforms=Array.isArray(b.platforms)?b.platforms.slice(0,12):u.platforms||[];u.onboardingComplete=Boolean(b.onboardingComplete);audit(d,u,'profile.updated');await save(d);return send(res,200,{user:{...safe(u),aliases:u.aliases,platforms:u.platforms}})}
  if(route==='/api/assets'&&req.method==='POST'){const b=await parse(req),raw=Buffer.from(b.data||'','base64');if(!b.name||!b.mime||!raw.length)return send(res,400,{error:'Missing file data.'});if(raw.length>8e6)return send(res,413,{error:'Local test limit: 8 MB per file.'});const id=randomUUID();await writeFile(path.join(VAULT,`${id}.vault`),vault(raw));const a={id,userId:u.id,name:String(b.name).slice(0,160),mime:String(b.mime).slice(0,80),size:raw.length,status:'Protected',createdAt:new Date().toISOString()};d.assets.push(a);audit(d,u,'vault.asset_added',{assetId:id,mime:a.mime,size:a.size});await save(d);return send(res,201,{asset:a})}
  if(route==='/api/scans'&&req.method==='POST'){const assets=d.assets.filter(x=>x.userId===u.id);if(!assets.length)return send(res,400,{error:'Add at least one reference asset before scanning.'});const scan={id:randomUUID(),userId:u.id,status:'Completed (sandbox)',mode:'sandbox',assets:assets.length,sourcesChecked:18402,matchesFound:4,startedAt:new Date().toISOString(),completedAt:new Date().toISOString()};d.scans.unshift(scan);audit(d,u,'scan.completed',{scanId:scan.id,mode:'sandbox'});await save(d);return send(res,201,{scan,matches:d.matches,notice:'Sandbox results only. No external websites were accessed.'})}
  if(route==='/api/billing/checkout'&&req.method==='POST'){const b=await parse(req),plans=['Monitor','Protect','Pro'];if(!plans.includes(b.plan))return send(res,400,{error:'Invalid plan.'});let sub=d.subscriptions.find(x=>x.userId===u.id);if(!sub){sub={id:randomUUID(),userId:u.id};d.subscriptions.push(sub)}Object.assign(sub,{plan:b.plan,status:'test_active',mode:'sandbox',renewalAt:null,updatedAt:new Date().toISOString()});u.plan=b.plan;audit(d,u,'billing.test_plan_selected',{plan:b.plan});await save(d);return send(res,200,{subscription:sub,user:safe(u),notice:'Test mode: no payment was taken.'})}
  if(route==='/api/cases'&&req.method==='POST'){const b=await parse(req),m=d.matches.find(x=>x.id===b.matchId);if(!m)return send(res,404,{error:'Match not found.'});const c={id:randomUUID(),userId:u.id,matchId:m.id,source:m.site,status:'Evidence review',mode:'sandbox',createdAt:new Date().toISOString(),timeline:[{event:'Evidence preserved',at:new Date().toISOString()},{event:'Awaiting creator approval',at:new Date().toISOString()}]};d.cases.push(c);m.status='Takedown sent';audit(d,u,'case.created',{caseId:c.id,matchId:m.id});await save(d);return send(res,201,{case:c,notice:'Sandbox only. No legal notice was sent.'})}
  send(res,404,{error:'Not found'});
}catch(e){console.error(e);send(res,500,{error:e.message==='large'?'Request too large.':'Something went wrong.'})}}).listen(PORT,'0.0.0.0',()=>console.log(`Content Protect API ready on port ${PORT}`));
